# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import kg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.filterEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.filterEdit.setGeometry(QtCore.QRect(180, 170, 131, 31))
        self.filterEdit.setObjectName("filterEdit")
        self.filterLabel = QtWidgets.QLabel(self.centralwidget)
        self.filterLabel.setGeometry(QtCore.QRect(10, 180, 91, 16))
        self.filterLabel.setObjectName("filterLabel")
        self.keywordLabel = QtWidgets.QLabel(self.centralwidget)
        self.keywordLabel.setGeometry(QtCore.QRect(10, 230, 131, 16))
        self.keywordLabel.setObjectName("keywordLabel")
        self.keywordsEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.keywordsEdit.setGeometry(QtCore.QRect(180, 220, 131, 31))
        self.keywordsEdit.setObjectName("keywordsEdit")
        self.createIndexCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.createIndexCheckbox.setGeometry(QtCore.QRect(10, 270, 101, 18))
        self.createIndexCheckbox.setObjectName("createIndexCheckbox")
        self.industryScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.industryScroll.setGeometry(QtCore.QRect(10, 30, 141, 111))
        self.industryScroll.setWidgetResizable(True)
        self.industryScroll.setObjectName("industryScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 139, 109))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.allIndustry = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.allIndustry.setGeometry(QtCore.QRect(10, 10, 83, 18))
        self.allIndustry.setObjectName("allIndustry")
        self.industryScroll.setWidget(self.scrollAreaWidgetContents)
        self.industryLabel = QtWidgets.QLabel(self.centralwidget)
        self.industryLabel.setGeometry(QtCore.QRect(10, 10, 47, 14))
        self.industryLabel.setObjectName("industryLabel")
        self.countriesLabel = QtWidgets.QLabel(self.centralwidget)
        self.countriesLabel.setGeometry(QtCore.QRect(190, 10, 47, 14))
        self.countriesLabel.setObjectName("countriesLabel")
        self.countriesScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.countriesScroll.setGeometry(QtCore.QRect(190, 30, 141, 111))
        self.countriesScroll.setWidgetResizable(True)
        self.countriesScroll.setObjectName("countriesScroll")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 139, 109))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.allCountry = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        self.allCountry.setGeometry(QtCore.QRect(10, 10, 83, 18))
        self.allCountry.setObjectName("allCountry")
        self.countriesScroll.setWidget(self.scrollAreaWidgetContents_3)
        self.sizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.sizeLabel.setGeometry(QtCore.QRect(390, 10, 71, 16))
        self.sizeLabel.setObjectName("sizeLabel")
        self.companySizeScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.companySizeScroll.setGeometry(QtCore.QRect(390, 30, 141, 111))
        self.companySizeScroll.setWidgetResizable(True)
        self.companySizeScroll.setObjectName("companySizeScroll")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 139, 109))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.allSize = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_5)
        self.allSize.setGeometry(QtCore.QRect(10, 10, 83, 18))
        self.allSize.setObjectName("allSize")
        self.companySizeScroll.setWidget(self.scrollAreaWidgetContents_5)
        self.findMatchesButton = QtWidgets.QPushButton(self.centralwidget)
        self.findMatchesButton.setGeometry(QtCore.QRect(0, 310, 161, 23))
        self.findMatchesButton.setObjectName("findMatchesButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 652, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filterLabel.setText(_translate("MainWindow", "URL Filters"))
        self.filterLabel.adjustSize()
        self.keywordLabel.setText(_translate("MainWindow", "Keywords To Search For"))
        self.keywordLabel.adjustSize()
        self.createIndexCheckbox.setText(_translate("MainWindow", "Create an Index"))
        self.allIndustry.setText(_translate("MainWindow", "All"))
        self.allIndustry.adjustSize()
        self.industryLabel.setText(_translate("MainWindow", "Industry"))
        self.industryLabel.adjustSize()
        self.countriesLabel.setText(_translate("MainWindow", "Countries"))
        self.countriesLabel.adjustSize()
        self.allCountry.setText(_translate("MainWindow", "All"))
        self.allCountry.adjustSize()
        self.sizeLabel.setText(_translate("MainWindow", "Company Size"))
        self.sizeLabel.adjustSize()
        self.allSize.setText(_translate("MainWindow", "All"))
        self.allSize.adjustSize()
        self.findMatchesButton.setText(_translate("MainWindow", "Find Matching Companies"))
        self.findMatchesButton.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    c=kg.Cache()
    c.loadCache()
    cache=c.getCache()
    MainWindow.show()
    sys.exit(app.exec_())

